mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  crossbar_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_arm_to_crossbar
    pid: {p: 0.0005, i: 0.008, d: 0.003}


  # Position Controllers ---------------------------------------
  arm_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_right_arm
    pid: {p: 5, i: 0.008, d: 1}


