#!/usr/bin/env python

import sys
import rospy
import numpy as np
from std_msgs.msg import Float64
from std_msgs.msg import Bool
from geometry_msgs.msg import Twist
from sensor_msgs.msg import LaserScan
from math import fabs

min_dist_ball = 1

class Navigator():
    def __init__(self):
        self.cmd_pub = rospy.Publisher('/cmd_vel', Twist, queue_size=1)
        self.delta_angle_sub = rospy.Subscriber('/mybot/delta_angle', Float64, self.delta_angle_callback)
        self.see_red_sub = rospy.Subscriber('/mybot/see_red', Bool, self.see_red_callback)
        self.scan_sub = rospy.Subscriber('/mybot/laser/scan', LaserScan, self.scan_callback)

        self.status = "init"
        self.delta_angle = None
        self.see_red = False
        self.saw_red = False
        self.covered = False
        self.scan = None
        self.view = {
                'right': float('Inf'),
                'fright': float('Inf'),
                'front_narrow': float('Inf'),
                'front_wide': float('Inf'),
                'fleft': float('Inf'),
                'left': float('Inf')
        }
        self.navigate()

    def delta_angle_callback(self, data):
        self.delta_angle = data.data

    def see_red_callback(self, data):
        self.see_red = data.data
        if self.see_red:
            self.saw_red = True

    def scan_callback(self, data):
        self.scan = data
        if self.scan is not None:
            self.view["front_narrow"] = min(self.scan.ranges[345:375])
            '''
            self.view['right'] = min(self.scan.ranges[270:306])
            self.view['fright'] = min(self.scan.ranges[306:342])
            self.view['front'] = min(self.scan.ranges[342:360]+self.scan.ranges[0:18])
            self.view['fleft'] = min(self.scan.ranges[18:54])
            self.view['left'] = min(self.scan.ranges[54:90])
            '''

    def command_bot(self, lx, ly, lz, ax, ay, az):
        twist = Twist()
        twist.linear.x = lx; twist.linear.y = ly; twist.linear.z = lz
        twist.angular.x = ax; twist.angular.y = ay; twist.angular.z = az
        self.cmd_pub.publish(twist)

    def change_status(self, input_status, info=None):
        if input_status != self.status:
            print "current: ", self.status, "   next: ", input_status
            if info is not None:
                print info
            self.status = input_status

    def init(self):
        if self.covered:
            self.change_status("terminated")
        else:
            self.change_status("searching")

    def search(self):
        if self.see_red:
            print "see red"
            self.change_status("moving_to_red")
        else:
            print "cannot see red"
            self.command_bot(0.3, 0, 0, 0, 0, 0)

    def move_to_red(self):
        if fabs(self.delta_angle) > 5 and self.view["front_narrow"] > min_dist_ball:
            linear = min(0.5, self.view["front_narrow"]*0.2)
            angular = min(0.5, self.delta_angle*0.01)
        elif fabs(self.delta_angle) <= 5 and self.view["front_narrow"] > min_dist_ball:
            linear = min(0.5, self.view["front_narrow"]*0.2)
            angular = 0
        elif fabs(self.delta_angle) > 5 and self.view["front_narrow"] <= min_dist_ball:
            linear = 0
            angular = min(0.5, self.delta_angle*0.01)
        else:
            linear = 0
            angular = 0
            self.change_status("terminated")
        self.command_bot(linear, 0, 0, 0, 0, angular)

    def grab(self):
        pass

    def retrieve(self):
        pass

    def move_to_src(self):
        pass

    def terminate(self):
        self.command_bot(0, 0, 0, 0, 0, 0)

    def navigate(self):
        rate = rospy.Rate(200)
        while not rospy.is_shutdown():
            if self.status == "init":
                self.init()
            elif self.status == "searching":
                self.search()
            elif self.status == "moving_to_red":
                self.move_to_red()
            elif self.status == "grabbing":
                self.grab()
            elif self.status == "retrieving":
                self.retrieve()
            elif self.status == "moving_to_src":
                self.moving_to_src()
            elif self.status == "terminated":
                self.terminate()
            else:
                print("unknown status")
            rate.sleep()

def main(args):
    rospy.init_node('navigator', anonymous=True)
    try:
        navigator = Navigator()
    except KeyboardInterrupt:
        print("Navigator Shutting down")

if __name__ == '__main__':
    main(sys.argv)