<?xml version="1.0" ?>
<robot name="turtlebot3_waffle" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mybot_description)/urdf/turtlebot/common_properties.xacro"/>
  <xacro:include filename="$(find mybot_description)/urdf/turtlebot/turtlebot3_waffle.gazebo.xacro"/>


   <xacro:property name="arm_mount_height" value="0.1" />
   <xacro:property name="arm_len" value="0.3" />
   <xacro:property name="arm_width" value="0.02" />
   <xacro:property name="arm_thick" value="0.01" />
   <xacro:property name="arm_dist" value="0.3" />
   <xacro:property name="camera_size" value="${arm_width*0.8}"/>
   <xacro:property name="default_mas" value="0.005" />


  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mybot_description/meshes/bases/waffle_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mybot_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mybot_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>


  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://mybot_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>


<!-- ********right arm***********-->
<joint name="base_to_right_arm" type="fixed">
    <parent link="base_link"/>
    <child link="right_arm"/>
    <origin xyz="${-0.15} ${arm_dist*0.5} ${arm_mount_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="right_arm">
    <visual>
      <origin xyz="${-arm_len*0.5} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${arm_len} ${arm_thick} ${arm_width}"/>
      </geometry>
      <material name="dark"/>
    </visual>

     <collision>
      <origin xyz="${-arm_len*0.5} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${arm_len} ${arm_thick} ${arm_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${default_mas}" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!--********left arm*******-->
<joint name="base_to_left_arm" type="fixed">
    <parent link="base_link"/>
    <child link="left_arm"/>
    <origin xyz="${-0.15} ${-arm_dist*0.5} ${arm_mount_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_arm">
    <visual>
      <origin xyz="${-arm_len*0.5} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${arm_len} ${arm_thick} ${arm_width}"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="${-arm_len*0.5} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${arm_len} ${arm_thick} ${arm_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${default_mas}" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!--*********cross bar********-->
<joint name="right_arm_to_crossbar" type="revolute">
    <parent link="right_arm"/>
    <child link="crossbar"/>
    <axis xyz="-1 0 0"/>
    <limit effort="100.0" lower="0.0" upper="3.14" velocity="0.1"/>
    <origin xyz="${-arm_len} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="crossbar">
    <visual>
      <origin xyz="0 ${-arm_dist*0.5} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${arm_thick} ${arm_dist + arm_width} ${arm_width}"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 ${-arm_dist*0.5} 0" rpy="0 0 0"/>
      <geometry>
	<box size="${arm_thick} ${arm_dist + arm_width} ${arm_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${default_mas}" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!-- **********************camera *************** -->

 <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.08 0 0.05" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera"/>
  </joint>

 <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="${default_mas}" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>



<transmission name="crossbar_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <actuator name="crossbar_motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    <joint name="right_arm_to_crossbar">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
  </transmission>



<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/mybot</robotNamespace>
 	<legacyModeNS>1</legacyModeNS> 
    <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>






  

</robot>
